### ISSUE TITLE
Input Types and Newline/Wrapping

### ISSUE THREAD

**Issue by krage** [piotrmurach/tty-markdown#19]
Some comments/suggestions sparked from the `gfm` mention here: https://github.com/piotrmurach/tty-markdown/pull/16#issuecomment-568202761

While `gfm` is mostly useful additions on top of standard markdown I don't think I'd choose it as the default since it causes single newline chars in text to inject `:br` elements into the doc (side note: maybe useful for that test case discussed in #15).  In normal markdown single newlines are just left as newlines in the text and are disregarded as that HTML is rendered on screen.  In the context of the rest of the current tty-markdown implementation this means with `gfm` mode single newlines within text input become double newlines in output.  The generated kramdown doc shows `gfm` producing the `:br` element and also keeping the `\n` in the following `:text` element:

```ruby
Kramdown::Document.new("foo\nbar", input:"Markdown").root.children
=> [<kd:p nil {:location=>1} [<kd:text "foo\nbar" nil {:location=>1}>]>]
Kramdown::Document.new("foo\nbar", input:"GFM").root.children
=> [<kd:p nil {:location=>1} [<kd:text "foo" nil {:location=>1}>, <kd:br nil {:location=>1}>, <kd:text "\nbar" nil {:location=>2}>]>]
```
Noting this led to trying some larger text-focused docs some of which had wrapped their markdown paragraphs to 80 columns with newlines (which again doesn't impact the HTML rendering).  I think the look and feel of that output would be improved by stripping newlines from `:text` elements.  This would more closely align the terminal output with the HTML rendered output.  Currently:
```ruby
Kramdown::Document.new("foo\nbar\nbaz", input:"Markdown").root.children
=> [<kd:p nil {:location=>1} [<kd:text "foo\nbar\nbaz" nil {:location=>1}>]>]
Kramdown::Document.new("foo\nbar\nbaz", input:"Markdown").to_html
=> "<p>foo\nbar\nbaz</p>\n"
TTY::Markdown.parse("foo\nbar\nbaz", input:"Markdown")
=> "foo\nbar\nbaz\n"
```
If space is available that HTML paragraph will render to a single line whereas tty-markdown output is split across 3 lines even with standard markdown input type and a very wide terminal.  Stripping these newlines probably has some consequences to manage with respect to width wrapping and indentation (and peeking at it there's an existing bug in `#convert_text` where indentation is being added after wrapping is applied which could extend lines beyond the specified width).

It'd be nice to also support disabling the built-in wrapping for long text elements so that modern terminals could do their own wrapping and reflow of full paragraphs.

Suggestion summary:
- `input: "Markdown"` as default, document availability of others
- strip newlines from text elements
- add option to disable addition of newlines that wrap long text to width

**Comment by piotrmurach** [comment]
On the general idea behind `tty-markdown` wrapping feature. It was meant to provide a nice way alternative to man documentation. Specifically, I wanted to have nicely formatted documents limited let's say to 80 characters regardless of terminal width. This is desirable, especially when working on HD wide terminals. Natural wrapping could be an option but wasn't a design goal at the start. The design was aimed at providing easy to read documentation for command-line tools.

As for motivation for the `gfm` parser. The most important benefit is code formatting. The `gfm` parser actually handles code samples with newlines. It provides langauge specification as part of parsing behaviour. Many people expect this, that's why it was reported as 'broken' when didn't behave this way. Github flavoured markup for many is the way markdown should work. The `kramdown` and `Markdown` formatters break and display code samples as unformatted paragraph of text including the fenced symbols. For example:

~~~ruby
template = <<~MSG
```ruby
def test

  puts "testing"

end
```
MSG

TTY::Markdown.parse(input: "Markdown")
# =>
# ```ruby
# def test
#
#   puts "testing"
#
# end
# ```
~~~

I consider the above as 'poor' and 'confusing' default. Especially, where the main point of this gem was to provide 'out-of-the-box' experience for formatting code samples. With the `GFM` parser:

~~~ruby
template = <<~MSG
```ruby
def test

  puts "testing"

end
```
MSG

TTY::Markdown.parse(input: "Markdown")
# => 'a colorful nicely formatted langauge specific output
# def test
#
#   puts "testing"
#
# end
~~~

As for the `br` element being added. When I tested the output on my little [example](https://github.com/piotrmurach/tty-markdown/blob/master/examples/example.md) I realised that it is actually beneficial to how output looks. Taking your example of `foo\nbar`. The previous implementation would do this:

```ruby
TTY::Markdown.parse("foo\nbar")
# =>
# foo
# bar
```
Which when displayed would have 2 lines that should be visually separated look like they are one paragraph. Considering new implementation:

```ruby
TTY::Markdown.parse("foo\nbar")
# =>
# foo
#
# bar
```
I believe this to be a more desirable outcome. Visually two separate lines get visually split into two separate lines in the terminal. Profit. The same goes for many other behaviours like dealing with headers followed immediately by content:

```ruby
TTY::Markdown.parse("#header\nsome copy")
# =>
# header
# some copy
```

The same now gets nicely split thanks to `br` being emitted:

```ruby
TTY::Markdown.parse("#header\nsome copy")
# =>
# header
#
# some copy
```

To me, the important bit is the final visual outcome and what may be expected by the users. I don't want people to be thinking about types of parsers but rather things to work out of the box. Inevitably, this will create issues for wrapping plain content as newlines will mean double output but we can handle this scenario when processing text paragraphs etc... For example, we could change `convert_br` to only inject new lines for certain elements and skip for others. You can check the type of parent element for the `br` element. Also, we can add metadata to text paragraphs that are wrapped vs regular newlines supplied by the user.

I'd rather have awesome looking code samples and tweak the paragraphs rather than the other way round. I'd happily leave parsing of codeblocks to `kramdown`. I'm in for the option to disable wrapping, it could be a special value for the `width` parameter like `false` or `:none`.

**Comment by piotrmurach** [comment]
Another alternative is to extract the code fencing logic out of the `GFM` parser and add it to the default one in `tty-markdown`.

**Comment by krage** [comment]
I agree that the output and what's expected by users is the important bit.  I maybe didn't do a great job with the `foo\nbar` example but output not matching expectations is what I was hoping to illustrate: 

- previously the default output was `foo\nbar`
- with the `gfm` default switch the new output is `foo\n\nbar`
- as a new user I'd actually expect to see `foo bar` according to standard markdown rules

I think changing to `gfm` as default is fine too as long as it's mentioned somewhat prominently in the readme.

---

So also in the context of `gfm` I think some of the newlines your examples present are still not what I'd expect.

In the `foo\nbar` example the complete html output produced by `kramdown` parsing that in `gfm` mode looks like:
```ruby
Kramdown::Document.new("foo\nbar", input:"GFM").to_html
=> "<p>foo<br />\nbar</p>\n"
```
I'd expect the terminal output to represent this single paragraph containing 1 line break the same way a browser would which is to say on just two lines: `foo\nbar\n`.

In `gfm` if you instead used a double newline like `foo\n\nbar` the html output is significantly different:
```ruby
Kramdown::Document.new("foo\n\nbar", input:"GFM").to_html
=> "<p>foo</p>\n\n<p>bar</p>\n"
```
Here I would expect the terminal output to be `foo\n\nbar\n`. The blank line makes it clear the surrounding lines are not part of the same single paragraph.

So currently in `gfm` mode both `foo\nbar` and `foo\n\nbar`, which mean different things in `gfm`, are resulting in identical output from `tty-markdown` which also isn't what I'd expect.

This is where my previous mention of stripping newlines from `:text` elements comes in. If you replace newlines plus all surrounding whitespace with a single space then both of these `gfm` situations and the regular `markdown` generate the output I'd expect.  The full change would be more complex than just a single gsub in order to manage indent/width features.

For the header example of `# header\nsome copy` the html output from `kramdown` is:
```ruby
Kramdown::Document.new("# header\nsome copy", input:"GFM").to_html
=> "<h1 id=\"header\">header</h1>\n<p>some copy</p>\n"
```
Again here I think an empty line between the header and paragraph is a reasonable translation.  I wanted to mention though that in my terminal using the current `tty-markdown` master branch here I'm getting just `header\nsome copy` without the blank line your example output included.  This probably needs to be changed at the end of `convert_header` to append a double newline?

---

New Summary:
- Choosing whatever default flavor is fine as long as it's documented prominently if the default isn't standard markdown.
- I think `tty-markdown`'s output should strive to mimic the overall formatting of the HTML output produced by typical markdown converters for whichever flavor(s) it supports.
- I suspect stripping newlines out of text elements is the easiest-to-maintain option for getting that portion of `tty-markdown`'s newline output to match the HTML equivalents across the various flavors `kramdown` will parse.

**Comment by piotrmurach** [comment]
I resumed work on this gem and I'm close to making a new release. I wanted to answer your points:

> * Choosing whatever default flavor is fine as long as it's documented prominently if the default isn't standard markdown.

I switched back to the default `kramdown` parser which is compatible with `Markdown` and adds a few extra elements like tables etc. I'm not going to expose the ability to change this as the `tty-markdown` is a whole tool that needs to work consistently out of the box. I completely scrapped the idea of `gfm` parser. I ported the `fenced` behaviour, for now, to make the code blocks work as expected.

> I think tty-markdown's output should strive to mimic the overall formatting of the HTML output produced by typical markdown converters for whichever flavor(s) it supports.

I'm not sure that this gem should strive to 'mimick' HTML output. There are some significant differences between the use cases of HTML rendering and rendering to the terminal. For example, I cannot let the text wrapping be handled by terminal. That wouldn't' work with how this tool styling works. For example, the blockquote or table formatting 'heavily' relies on the terminal width constraint as well as indentation for each paragraph. It would almost impossible to provide sensible formatting, at least the way I want it to be by having terminal handle the wrapping. By default, the wrapping is set to be automatic and span the entire terminal width.

> * I suspect stripping newlines out of text elements is the easiest-to-maintain option for getting that portion of tty-markdown's newline output to match the HTML equivalents across the various flavors kramdown will parse.

I don't think this is desirable. If a user provides input where they specifically want to break blockquote element by a newline, I don't think that `tty-markdow` should modify and strip any tabs or newline characters. The HTML is a different medium in so far as controlling output format goes.  

I really appreciate your help and reading this thread was a great reminder as to what needed to change and what I need to focus on.
